services:
  mariadb:
    image: mariadb:11.7.2
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: compartetutiempo
      MARIADB_USER: compartetutiempo
      MARIADB_PASSWORD: compartetutiempo
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - appnet

  backend:
    build: .
    container_name: backend
    depends_on:
      - mariadb
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    restart: always
    networks:
      - appnet

  compartetiempo:
    compartetutiempo:
      build: ./frontend
      container_name: compartetutiempo
      depends_on:
        - backend
      ports:
        - "80:80"
      restart: always
      networks:
        - appnet

volumes:
  mariadb_data:

networks:
  appnet:
    driver: bridge
