name: Build and Push Docker Images on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build -f Dockerfile -t $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:${RELEASE_VERSION} ./
          docker tag $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:${RELEASE_VERSION} $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:latest

      - name: Build frontend image
        run: |
          docker build -f frontend/Dockerfile -t $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:${RELEASE_VERSION} ./frontend
          docker tag $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:${RELEASE_VERSION} $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:latest

      - name: Push backend image
        run: |
          docker push $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:${RELEASE_VERSION}
          docker push $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:latest

      - name: Push frontend image
        run: |
          docker push $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:${RELEASE_VERSION}
          docker push $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:latest
