name: Build and Push Docker Images on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set RELEASE_VERSION
        id: set_release_version
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            # Obtener el tag de la última release publicada
            LATEST_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
            echo "RELEASE_VERSION=$LATEST_TAG" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build -f Dockerfile -t $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:${RELEASE_VERSION} ./
          docker tag $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:${RELEASE_VERSION} $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:latest

      - name: Build frontend image
        run: |
          docker build -f frontend/Dockerfile -t $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:${RELEASE_VERSION} ./frontend
          docker tag $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:${RELEASE_VERSION} $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:latest

      - name: Push backend image
        run: |
          docker push $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:${RELEASE_VERSION}
          docker push $DOCKERHUB_USERNAME/comparte-tu-tiempo-backend:latest

      - name: Push frontend image
        run: |
          docker push $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:${RELEASE_VERSION}
          docker push $DOCKERHUB_USERNAME/comparte-tu-tiempo-frontend:latest
